# Generated by Django 5.2.17 on 2026-08-23 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('buh_structure_ops', '0002_granular_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRoleConfiguration',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('director_group', models.ForeignKey(help_text='Existing Auth group that receives full Structure Operations access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.group', verbose_name='Director-default Auth / Discord role')),
                ('member_group', models.ForeignKey(help_text='Existing Auth group that receives the safe member defaults.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.group', verbose_name='Member-default Auth / Discord role')),
            ],
            options={
                'verbose_name': 'Structure Operations role settings',
                'verbose_name_plural': 'Structure Operations role settings',
            },
        ),
    ]
