# Generated by Django 5.2.17 on 2026-08-23 02:08

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('buh_mining_analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiningAccessGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Mining Analytics access group',
                'verbose_name_plural': 'Mining Analytics access groups',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='mininganalyticspermission',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can access Mining Analytics and view own characters'), ('view_corporation', 'Can view Mining Analytics for members of the same corporation'), ('view_all', 'Can view Mining Analytics for all registered characters'), ('export_data', 'Can export Mining Analytics data within allowed scope'), ('manage_access', 'Can manage Mining Analytics access groups in Django admin'))},
        ),
    ]
