# Generated by Django 5.2.17 on 2026-08-29 23:36

import uuid

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryArchivePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_history_archive', 'Can open ESI History Archive'), ('view_archive_storage', 'Can view archive storage totals'), ('view_archive_coverage', 'Can view endpoint and dataset coverage'), ('view_public_archive', 'Can view public archive metadata'), ('view_private_archive_metadata', 'Can view private ESI archive metadata'), ('download_public_archive', 'Can download archived public payloads'), ('download_private_archive', 'Can download archived private payloads'), ('run_public_archive_sync', 'Can catalog and synchronize public datasets'), ('manage_archive_settings', 'Can configure ESI History Archive'), ('manage_archive_access', 'Can administer ESI History Archive access')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PublicDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('index_url', models.URLField(max_length=700, unique=True)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=100)),
                ('last_catalog_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='HistoryArchiveAccessGroup',
            fields=[
            ],
            options={
                'verbose_name': 'ESI History Archive access group',
                'verbose_name_plural': 'ESI History Archive access groups',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveCaptureIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.CharField(blank=True, default='', max_length=180)),
                ('reason', models.CharField(db_index=True, max_length=80)),
                ('detail', models.CharField(blank=True, default='', max_length=500)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ('-last_seen_at',),
                'constraints': [models.UniqueConstraint(fields=('operation_id', 'reason', 'detail'), name='buh_history_unique_capture_issue')],
            },
        ),
        migrations.CreateModel(
            name='ArchiveConfiguration',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('capture_enabled', models.BooleanField(default=True)),
                ('capture_public_esi', models.BooleanField(default=True)),
                ('capture_private_esi', models.BooleanField(default=True)),
                ('max_response_mib', models.PositiveIntegerField(default=512, help_text='Responses above this size are recorded as skipped metadata, not payload files.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2048)])),
                ('minimum_free_gib', models.PositiveIntegerField(default=25, help_text='Archiving pauses before the host drops below this much free space.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(2048)])),
                ('public_mirror_enabled', models.BooleanField(default=True)),
                ('public_max_files_per_run', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)])),
                ('public_max_gib_per_run', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ESI History Archive configuration',
                'verbose_name_plural': 'ESI History Archive configuration',
            },
        ),
        migrations.CreateModel(
            name='ArchiveJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('CATALOG', 'Catalog public datasets'), ('SYNC', 'Synchronize public datasets'), ('VERIFY', 'Verify archive files')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buh_archive_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='ArchiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_key', models.CharField(max_length=64, unique=True)),
                ('operation_id', models.CharField(db_index=True, max_length=180)),
                ('method', models.CharField(default='GET', max_length=12)),
                ('url_template', models.CharField(max_length=500)),
                ('safe_parameters', models.JSONField(blank=True, default=dict)),
                ('app_name', models.CharField(blank=True, default='', max_length=160)),
                ('is_private', models.BooleanField(db_index=True, default=False)),
                ('character_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('auth_user_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('request_count', models.PositiveBigIntegerField(default=0)),
                ('snapshot_count', models.PositiveIntegerField(default=0)),
                ('source_bytes', models.PositiveBigIntegerField(default=0)),
                ('stored_bytes', models.PositiveBigIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('current_payload_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('last_status_code', models.PositiveSmallIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ('-last_seen_at',),
                'indexes': [models.Index(fields=['is_private', '-last_seen_at'], name='buh_max_his_is_priv_30ef21_idx'), models.Index(fields=['operation_id', '-last_seen_at'], name='buh_max_his_operati_bf2f9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArchiveSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_sha256', models.CharField(max_length=64)),
                ('relative_path', models.CharField(max_length=700)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('source_bytes', models.PositiveBigIntegerField(default=0)),
                ('stored_bytes', models.PositiveBigIntegerField(default=0)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('first_observed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_observed_at', models.DateTimeField(auto_now=True)),
                ('observation_count', models.PositiveBigIntegerField(default=1)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='buh_max_history.archivestream')),
            ],
            options={
                'ordering': ('-first_observed_at',),
                'indexes': [models.Index(fields=['stream', '-first_observed_at'], name='buh_max_his_stream__dda1d9_idx')],
                'constraints': [models.UniqueConstraint(fields=('stream', 'payload_sha256'), name='buh_history_unique_stream_payload')],
            },
        ),
        migrations.CreateModel(
            name='PublicArchiveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=900, unique=True)),
                ('relative_path', models.CharField(max_length=700)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DOWNLOADING', 'Downloading'), ('STORED', 'Stored'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('remote_size', models.PositiveBigIntegerField(default=0)),
                ('stored_bytes', models.PositiveBigIntegerField(default=0)),
                ('payload_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('etag', models.CharField(blank=True, default='', max_length=300)),
                ('remote_modified', models.CharField(blank=True, default='', max_length=120)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='buh_max_history.publicdataset')),
            ],
            options={
                'ordering': ('dataset__priority', 'source_url'),
                'indexes': [models.Index(fields=['status', 'dataset'], name='buh_max_his_status_5cba6d_idx')],
            },
        ),
    ]
