# Generated by Django 5.2 on 2026-08-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buh_max_history", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicCatalogIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_url", models.URLField(max_length=900)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CATALOGED", "Cataloged"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("depth", models.PositiveSmallIntegerField(default=0)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_catalog_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_checked_at", models.DateTimeField(auto_now=True)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indexes",
                        to="buh_max_history.publicdataset",
                    ),
                ),
            ],
            options={
                "ordering": ("depth", "source_url"),
                "indexes": [
                    models.Index(
                        fields=["dataset", "status", "last_catalog_at"],
                        name="buh_max_his_dataset_14c791_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset", "source_url"),
                        name="buh_history_unique_dataset_index",
                    )
                ],
            },
        ),
    ]
