# Generated by Django 5.2.17 on 2026-09-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buh_max_history', '0002_publiccatalogindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveconfiguration',
            name='public_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicarchivefile',
            name='failure_count',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='publicarchivefile',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='publicarchivefile',
            name='retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='publiccatalogindex',
            name='catalog_sha256',
            field=models.CharField(blank=True, db_default='', max_length=64),
        ),
        migrations.AddField(
            model_name='publiccatalogindex',
            name='cursor',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='publicdataset',
            name='download_turn',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
    ]
