# Generated by Django 5.2.17 on 2026-09-13 19:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buh_max_history", "0003_archiveconfiguration_public_retry_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveCollectionTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("kind", models.CharField(db_index=True, default="esi", max_length=12)),
                ("operation_id", models.CharField(db_index=True, max_length=180)),
                ("parameters", models.JSONField(default=dict)),
                (
                    "character_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "corporation_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(db_index=True, default="pending", max_length=32),
                ),
                ("cursor", models.JSONField(blank=True, default=dict)),
                (
                    "next_attempt_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("detail", models.CharField(blank=True, default="", max_length=500)),
            ],
            options={
                "ordering": ("next_attempt_at", "pk"),
            },
        ),
        migrations.AddField(
            model_name="archiveconfiguration",
            name="active_esi_enabled",
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name="archiveconfiguration",
            name="active_requests_per_run",
            field=models.PositiveSmallIntegerField(
                db_default=120,
                default=120,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(2000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="archiveconfiguration",
            name="active_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="archiveconfiguration",
            name="discover_public_datasets",
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name="archiveconfiguration",
            name="discovery_character_cursor",
            field=models.PositiveBigIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="archiveconfiguration",
            name="last_public_discovery_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="archiveconfiguration",
            name="local_history_enabled",
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name="archiveconfiguration",
            name="local_rows_per_run",
            field=models.PositiveIntegerField(db_default=500, default=500),
        ),
        migrations.CreateModel(
            name="ArchiveObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_observed_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "last_observed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("observation_count", models.PositiveBigIntegerField(default=1)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="buh_max_history.archivesnapshot",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="buh_max_history.archivestream",
                    ),
                ),
            ],
            options={
                "ordering": ("-pk",),
                "indexes": [
                    models.Index(
                        fields=["stream", "-id"], name="buh_max_his_stream__6ed8df_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PublicArchiveRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload_sha256", models.CharField(max_length=64)),
                ("relative_path", models.CharField(max_length=700)),
                ("stored_bytes", models.PositiveBigIntegerField(default=0)),
                (
                    "first_observed_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "last_observed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="buh_max_history.publicarchivefile",
                    ),
                ),
            ],
            options={
                "ordering": ("-pk",),
                "indexes": [
                    models.Index(
                        fields=["file", "-id"], name="buh_max_his_file_id_90cd26_idx"
                    )
                ],
            },
        ),
    ]
