# Generated by Django 5.2.17 on 2026-09-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buh_max_history", "0005_schedule_history_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicarchivefile",
            name="source_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
