# Generated by Django 5.2.17 on 2026-08-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buh_vps_health', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vpshealthpermission',
            options={'default_permissions': (), 'managed': False, 'permissions': (('view_vps_health', 'Can open VPS Health'), ('view_host_metrics', 'Can view VPS resource metrics'), ('view_container_metrics', 'Can view Docker container metrics'), ('view_worker_workload', 'Can view Celery worker workload'), ('view_task_queue', 'Can view Celery queue details'), ('view_action_history', 'Can view guarded operation history'), ('check_updates', 'Can run a read-only update scan'), ('view_update_results', 'Can view detailed update scan results'), ('restart_auth_services', 'Can restart Alliance Auth services'), ('scale_workers', 'Can add or remove Alliance Auth workers'), ('manage_health_settings', 'Can configure health thresholds and alerts'), ('manage_health_access', 'Can administer VPS Health access'))},
        ),
        migrations.AddField(
            model_name='operationalaction',
            name='result_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='operationalaction',
            name='action',
            field=models.CharField(choices=[('RESTART_AUTH', 'Restart Auth services'), ('SET_WORKERS', 'Set worker count'), ('CHECK_UPDATES', 'Check all updates')], db_index=True, max_length=24),
        ),
    ]
