# Generated by Django 5.2.17 on 2026-08-24 02:01

from decimal import Decimal

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoonTaxPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_moon_tax', 'Can open the Moon Tax application'), ('view_own_tax', 'Can see own account and character tax records'), ('view_all_tax', 'Can see all linked account tax records'), ('view_unlinked_miners', 'Can see unlinked and outside miners'), ('view_mining_quantities', 'Can see mined ore types and quantities'), ('view_mining_values', 'Can see Jita valuations and calculated tax'), ('view_payment_evidence', 'Can see payment evidence and review history'), ('run_tax_audit', 'Can start a moon tax audit'), ('review_payments', 'Can approve, reject, split, or classify payments'), ('manage_tax_policy', 'Can edit tax rates, periods, and compression rules'), ('manage_exemptions', 'Can add, change, and end tax exemptions'), ('manage_enforcement', 'Can configure future tax enforcement rules'), ('export_tax_data', 'Can export allowed Moon Tax data'), ('manage_access', 'Can manage Moon Tax access groups')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CompressionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_type_id', models.PositiveIntegerField(unique=True)),
                ('raw_type_name', models.CharField(max_length=255)),
                ('compressed_type_id', models.PositiveIntegerField(db_index=True)),
                ('compressed_type_name', models.CharField(max_length=255)),
                ('raw_units', models.PositiveIntegerField(default=100)),
                ('compressed_units', models.PositiveIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ore compression rule',
                'verbose_name_plural': 'ore compression rules',
                'ordering': ('raw_type_name',),
            },
        ),
        migrations.CreateModel(
            name='NotificationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=255, unique=True)),
                ('last_sent_at', models.DateTimeField()),
                ('payload_hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MoonTaxAccessGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Moon Tax access group',
                'verbose_name_plural': 'Moon Tax access groups',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('MANUAL', 'Manual button'), ('SCHEDULED', 'Scheduled'), ('INSTALL', 'Installation / backfill')], max_length=12)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('REFRESHING', 'Refreshing ESI sources'), ('RUNNING', 'Reconciling'), ('COMPLETE', 'Complete'), ('WARNING', 'Complete with warnings'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=12)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('source_refresh_requested_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buh_moon_tax_audits_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-queued_at',),
            },
        ),
        migrations.CreateModel(
            name='BillingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combine_characters', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buh_moon_tax_billing_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnforcementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('overdue_days', models.PositiveSmallIntegerField(default=7)),
                ('minimum_outstanding', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=30)),
                ('action', models.CharField(choices=[('NOTIFY', 'Notify only'), ('REMOVE_GROUP', 'Remove an Auth group'), ('ADD_GROUP', 'Add an Auth group')], default='NOTIFY', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.group')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('WALLET', 'Direct wallet payment'), ('CONTRACT', 'Completed ISK contract'), ('MANUAL', 'Director-entered manual credit')], max_length=12)),
                ('source_key', models.CharField(max_length=180, unique=True)),
                ('source_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('payer_character_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('payer_character_name', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_id', models.PositiveBigIntegerField()),
                ('recipient_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved and allocated'), ('PARTIAL', 'Partially allocated'), ('REJECTED', 'Rejected'), ('DONATION', 'Donation'), ('OVERAGE', 'Accepted overage / carry-forward'), ('IGNORED', 'Ignored')], db_index=True, default='PENDING', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('auth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buh_moon_tax_payments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buh_moon_tax_manual_payments', to=settings.AUTH_USER_MODEL)),
                ('imported_by_audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_candidates', to='buh_moon_tax.auditrun')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buh_moon_tax_payments_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compressed_type_id', models.PositiveIntegerField(db_index=True)),
                ('compressed_type_name', models.CharField(max_length=255)),
                ('requested_quantity', models.DecimalField(decimal_places=8, max_digits=30)),
                ('priced_quantity', models.DecimalField(decimal_places=8, max_digits=30)),
                ('weighted_unit_price', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=30)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=30)),
                ('region_id', models.PositiveBigIntegerField(default=10000002)),
                ('location_id', models.PositiveBigIntegerField(default=60003760)),
                ('source', models.CharField(default='ESI Jita buy orders', max_length=80)),
                ('complete', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('raw_evidence', models.JSONField(blank=True, default=dict)),
                ('audit_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='buh_moon_tax.auditrun')),
            ],
            options={
                'ordering': ('compressed_type_name',),
            },
        ),
        migrations.CreateModel(
            name='StructureTaxPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_id', models.PositiveBigIntegerField(db_index=True)),
                ('structure_name', models.CharField(max_length=255)),
                ('corporation_id', models.PositiveBigIntegerField(db_index=True)),
                ('corporation_name', models.CharField(max_length=255)),
                ('tax_rate', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal(0)), django.core.validators.MaxValueValidator(Decimal(100))])),
                ('effective_from', models.DateTimeField(db_index=True)),
                ('effective_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'refinery tax policy',
                'verbose_name_plural': 'refinery tax policies',
                'ordering': ('structure_name', '-effective_from'),
            },
        ),
        migrations.CreateModel(
            name='TaxAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_key', models.CharField(max_length=80)),
                ('character_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('display_name', models.CharField(max_length=255)),
                ('combined_characters', models.BooleanField(default=True)),
                ('gross_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=30)),
                ('tax_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=30)),
                ('approved_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=30)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DUE', 'Due'), ('PARTIAL', 'Partially paid'), ('PAID', 'Paid'), ('EXEMPT', 'Exempt'), ('REVIEW', 'Needs review')], db_index=True, default='OPEN', max_length=12)),
                ('due_at', models.DateTimeField()),
                ('first_notified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buh_moon_tax_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('period__pop_at', 'display_name'),
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TAX', 'Apply to selected extraction tax'), ('CARRYOVER', 'Carry forward to future tax'), ('OVERAGE', 'Accept as overage'), ('DONATION', 'Donation'), ('IGNORED', 'Ignore amount')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buh_moon_tax_allocations_created', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='buh_moon_tax.paymentcandidate')),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='buh_moon_tax.taxassessment')),
            ],
            options={
                'ordering': ('payment', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('default_tax_rate', models.DecimalField(decimal_places=4, default=Decimal('5.0000'), help_text='Percentage used when a refinery has no effective override.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal(0)), django.core.validators.MaxValueValidator(Decimal(100))])),
                ('mining_window_days', models.PositiveSmallIntegerField(default=3, help_text='A pull accepts observer-ledger mining through this many days after pop.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)])),
                ('audit_interval_hours', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('combine_characters_by_default', models.BooleanField(default=True)),
                ('pricing_mode', models.CharField(choices=[('JITA_BUY', 'Jita 4-4 buy-order value')], default='JITA_BUY', max_length=20)),
                ('pricing_region_id', models.PositiveBigIntegerField(default=10000002)),
                ('pricing_location_id', models.PositiveBigIntegerField(default=60003760)),
                ('payment_character_id', models.PositiveBigIntegerField(default=0)),
                ('payment_character_name', models.CharField(default='Fifty5D', max_length=255)),
                ('payment_corporation_id', models.PositiveBigIntegerField(default=0)),
                ('payment_corporation_name', models.CharField(default='Bureau of Unified Harvesting', max_length=255)),
                ('notify_member_new_tax', models.BooleanField(default=True)),
                ('notify_member_payment_decision', models.BooleanField(default=True)),
                ('notify_director_unpaid', models.BooleanField(default=True)),
                ('notify_director_missing_data', models.BooleanField(default=True)),
                ('enforcement_enabled', models.BooleanField(default=False, help_text='Master switch. The release installer intentionally leaves this off.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moon Tax configuration',
                'verbose_name_plural': 'Moon Tax configuration',
            },
        ),
        migrations.CreateModel(
            name='TaxExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('character_name', models.CharField(blank=True, default='', max_length=255)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_until', models.DateField(blank=True, db_index=True, null=True)),
                ('reason', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buh_moon_tax_exemptions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buh_moon_tax_exemptions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-effective_from', 'character_name'),
            },
        ),
        migrations.CreateModel(
            name='TaxPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_started_at', models.DateTimeField()),
                ('structure_id', models.PositiveBigIntegerField(db_index=True)),
                ('structure_name', models.CharField(max_length=255)),
                ('corporation_id', models.PositiveBigIntegerField(db_index=True)),
                ('corporation_name', models.CharField(max_length=255)),
                ('moon_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('moon_name', models.CharField(blank=True, default='', max_length=255)),
                ('extraction_started_at', models.DateTimeField()),
                ('pop_at', models.DateTimeField(db_index=True)),
                ('closes_at', models.DateTimeField(db_index=True)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('tax_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('status', models.CharField(choices=[('OPEN', 'Collecting mining'), ('DUE', 'Closed and due'), ('SETTLED', 'Settled'), ('CANCELED', 'Canceled'), ('REVIEW', 'Needs data review')], db_index=True, default='OPEN', max_length=12)),
                ('gross_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=30)),
                ('tax_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=30)),
                ('approved_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_audit_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods', to='buh_moon_tax.auditrun')),
            ],
            options={
                'ordering': ('-pop_at', 'structure_name'),
            },
        ),
        migrations.AddField(
            model_name='taxassessment',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='buh_moon_tax.taxperiod'),
        ),
        migrations.CreateModel(
            name='MiningLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_day', models.DateField(db_index=True)),
                ('character_id', models.PositiveBigIntegerField(db_index=True)),
                ('character_name', models.CharField(max_length=255)),
                ('recorded_corporation_id', models.PositiveBigIntegerField(db_index=True)),
                ('recorded_corporation_name', models.CharField(max_length=255)),
                ('raw_type_id', models.PositiveIntegerField()),
                ('raw_type_name', models.CharField(max_length=255)),
                ('compressed_type_id', models.PositiveIntegerField(blank=True, null=True)),
                ('compressed_type_name', models.CharField(blank=True, default='', max_length=255)),
                ('raw_quantity', models.PositiveBigIntegerField()),
                ('compressed_quantity', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=30)),
                ('compressed_unit_price', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=30)),
                ('gross_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=30)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=7)),
                ('tax_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=30)),
                ('is_exempt', models.BooleanField(default=False)),
                ('exemption_reason', models.CharField(blank=True, default='', max_length=500)),
                ('pricing_complete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buh_moon_tax_mining', to=settings.AUTH_USER_MODEL)),
                ('last_audit_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mining_lines', to='buh_moon_tax.auditrun')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mining_lines', to='buh_moon_tax.taxperiod')),
            ],
            options={
                'ordering': ('ledger_day', 'character_name', 'raw_type_name'),
            },
        ),
        migrations.AddIndex(
            model_name='paymentcandidate',
            index=models.Index(fields=['auth_user', 'status', 'occurred_at'], name='buh_moon_ta_auth_us_9e15ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricesnapshot',
            constraint=models.UniqueConstraint(fields=('audit_run', 'compressed_type_id'), name='buh_moon_tax_price_run_type_unique'),
        ),
        migrations.AddIndex(
            model_name='structuretaxpolicy',
            index=models.Index(fields=['structure_id', 'effective_from'], name='buh_moon_ta_structu_8fec6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='structuretaxpolicy',
            constraint=models.UniqueConstraint(fields=('structure_id', 'effective_from'), name='buh_moon_tax_policy_effective_unique'),
        ),
        migrations.AddConstraint(
            model_name='taxexemption',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('auth_user__isnull', False), ('character_id__isnull', True)), models.Q(('auth_user__isnull', True), ('character_id__isnull', False)), _connector='OR'), name='buh_moon_tax_exemption_exact_target'),
        ),
        migrations.AddIndex(
            model_name='taxperiod',
            index=models.Index(fields=['status', 'due_at'], name='buh_moon_ta_status_fc076b_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxperiod',
            constraint=models.UniqueConstraint(fields=('structure_id', 'source_started_at'), name='buh_moon_tax_period_source_unique'),
        ),
        migrations.AddIndex(
            model_name='taxassessment',
            index=models.Index(fields=['status', 'due_at'], name='buh_moon_ta_status_218ebc_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxassessment',
            constraint=models.UniqueConstraint(fields=('period', 'billing_key'), name='buh_moon_tax_assessment_key_unique'),
        ),
        migrations.AddIndex(
            model_name='miningline',
            index=models.Index(fields=['auth_user', 'ledger_day'], name='buh_moon_ta_auth_us_e1d597_idx'),
        ),
        migrations.AddIndex(
            model_name='miningline',
            index=models.Index(fields=['character_id', 'ledger_day'], name='buh_moon_ta_charact_f26fbb_idx'),
        ),
        migrations.AddConstraint(
            model_name='miningline',
            constraint=models.UniqueConstraint(fields=('period', 'ledger_day', 'character_id', 'raw_type_id'), name='buh_moon_tax_mining_line_unique'),
        ),
    ]
