# Generated by Django 5.2.17 on 2026-08-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buh_moon_tax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxperiod',
            name='allowed_recipients',
            field=models.JSONField(blank=True, default=list, help_text='Immutable character/corporation payment recipients for this pull.'),
        ),
        migrations.CreateModel(
            name='PaymentRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CHARACTER', 'Character'), ('CORPORATION', 'Corporation')], max_length=12)),
                ('entity_id', models.PositiveBigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('discovered_from_auth', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'allowed tax recipient',
                'verbose_name_plural': 'allowed tax recipients',
                'ordering': ('kind', 'name'),
                'constraints': [models.UniqueConstraint(fields=('kind', 'entity_id'), name='buh_moon_tax_recipient_kind_id_unique')],
            },
        ),
        migrations.AddField(
            model_name='structuretaxpolicy',
            name='payment_recipients',
            field=models.ManyToManyField(blank=True, help_text='Checked recipients are valid for this Athanor. Leave empty to inherit the installation default checklist.', related_name='structure_policies', to='buh_moon_tax.paymentrecipient'),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='default_payment_recipients',
            field=models.ManyToManyField(blank=True, help_text='Used by a refinery when its effective policy has no custom recipient checklist. Each extraction snapshots the effective list.', related_name='default_for_configurations', to='buh_moon_tax.paymentrecipient'),
        ),
    ]
