# Generated by Django 5.2.17 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buh_moon_tax", "0002_taxperiod_allowed_recipients_paymentrecipient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentcandidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending review"),
                    ("APPROVED", "Approved and allocated"),
                    ("PARTIAL", "Partially allocated"),
                    ("REJECTED", "Rejected"),
                    ("DONATION", "Donation"),
                    ("OVERAGE", "Accepted overage / carry-forward"),
                    ("IGNORED", "Ignored"),
                    ("EXEMPT", "Excluded by exemption"),
                ],
                db_index=True,
                default="PENDING",
                max_length=12,
            ),
        ),
    ]
